### ISSUE TITLE
[Issue]: RAG Flow has Collection name hardcoded

### ISSUE THREAD

**Issue by Jayaprakash8887** [OpenNyAI/Jugalbandi-Manager#113]
### Describe the issue

'KB_Law_Files' is hardcoded as collection_name in RAG

![image](https://github.com/OpenNyAI/Jugalbandi-Manager/assets/19702246/85a2b095-05d3-4a8e-a9b4-72a10b136de2)

### Steps to reproduce

flow/src/__main__.py

**Comment by Jayaprakash8887** [comment]
cc: @sajesh@tarento.com @vaibhav.bhuva@tarento.com

**Comment by sameersegal** [comment]
Yes, thank you for pointing this out. 

@KaranrajM can you please post an urgent fix for this.

**Comment by KaranrajM** [comment]
Yes, just started working on it. Will raise a PR soon.

**Comment by shreypandey** [comment]
We have fixed this in #141
