### ISSUE TITLE
[Issue]: Indexer service is expecting files to be indexed to be available in ./data folder of container

### ISSUE THREAD

**Issue by Jayaprakash8887** [OpenNyAI/Jugalbandi-Manager#114]
### Describe the issue

docker-compose.yml 

### Screenshots and logs

![image](https://github.com/OpenNyAI/Jugalbandi-Manager/assets/19702246/68be013b-2842-4354-873f-5aacdc7b3052)

**Comment by sameersegal** [comment]
@KaranrajM can you please look into this. You can discuss with @shreypandey. We have made storage configurable

**Comment by KaranrajM** [comment]
Hi, @DevvStrange was working on this, which is the same as issue #73 . Let me take a hold of the current status and update it here.

**Comment by KaranrajM** [comment]
Closing PR #151 will close this issue.
