### ISSUE TITLE
[Bug]: Issue with multiple inputs while in a state

### ISSUE THREAD

**Issue by varun-heman** [OpenNyAI/Jugalbandi-Manager#14]
### Describe the bug

While in a state, if the user sends multiple messages, the bot can end up producing junk and sending back a range of responses, sometimes even resetting the state.

### Steps to reproduce

In any state, send more than one message to the bot.

### Expected Behavior

Bot should ideally terminate earlier request and resend request with new context/messages and process once.

**Comment by Lekhanrao** [comment]
@varun-heman, I dont see this issue assigned to anybody as yet. Is this bug still existing? Could you please provide an update.

**Comment by KaranrajM** [comment]
Closing this issue and moved the content to #12
