### ISSUE TITLE
[Feature Request]: Integration of frontend with v2 Routes

### ISSUE THREAD

**Issue by shreypandey** [OpenNyAI/Jugalbandi-Manager#152]
### Is your feature request related to a problem? Please describe.

Currently, JB manager only support whatsapp channel which is populating in JBChannel while activating the bot. There is no feature to manually add channels through JBManager frontend.

### Describe the solution you'd like

Currently, there exist the following API's in `/v2` of JB Manager. 
1. Add channel to bot
2. Edit Channel
3. Activate Channel
4. Deactivate Channel
5. Delete Channel
6. List Available Channels

There should be a support of using these API using the JBManager frontend. Appropriate UI changes should be required to incorporate this.

**Comment by abhaymathur21** [comment]
I can work on this

**Comment by sm98** [comment]
![JB Manager](https://github.com/user-attachments/assets/379b7234-8c87-4bc0-a59b-b1391fb788b4)
![Channel Config](https://github.com/user-attachments/assets/2ff4d419-6ee9-4c7c-a847-0d944d9d1f04)
![Channel selection](https://github.com/user-attachments/assets/b22793ed-1f96-43e4-830f-3b99828e21ba)
Mock Ui

**Comment by shreypandey** [comment]
@sm98 Can you please add all the mocks and flows in this issue?

**Comment by shreypandey** [comment]
@mx-om @code-with-om will you be able to take up this issue?

**Comment by code-with-om** [comment]
@shreypandey sure, I can work on this. But can you please explain the task that we are trying to implement here ? Because, as above, I can see some tasks are already done.

**Comment by sm98** [comment]
![ChannelConfig06](https://github.com/user-attachments/assets/c065622b-8bd9-4dcd-a7d3-3fe2a03d5faf)
Updated Mockup. 

User can access this screen from left navigation bar within the project. 
This ui enables multiple bots in same channel (whatsapp, telegram, etc) in a compact view.
User can add, enable, disable, delete and edit channels.

**Comment by Lekhanrao** [comment]
@abhaymathur21, Any update on this please?

**Comment by shreypandey** [comment]
@Lekhanrao This is same as #176

**Comment by Lekhanrao** [comment]
Karan spoke with Shrey and we understand that #152 will be closed once #176 is completed. #176 is assigned to ris-code at this time and he is working on it.

**Comment by Lekhanrao** [comment]
@KaranrajM to review the PR and close by this Friday 4th Oct
