### ISSUE TITLE
[Feature Request]: Fix 'Add Project' button UI

### ISSUE THREAD

**Issue by sm98** [OpenNyAI/Jugalbandi-Manager#166]
### Describe the solution you'd like

![JB Manager](https://github.com/user-attachments/assets/aca23246-12ff-4f06-911e-207f4fb57c3e)

Please fix UI for 'Add Project' button

**Comment by shreypandey** [comment]
Required changes:
1. Remove `Install New Bot` button in frontend.
2. Add `Add Project` button as shown in UI mock.
3. Transfer the functionalities of `Install New Bot` to `Add Project`

**Comment by shreypandey** [comment]
@mx-om Will you be able to take it up?

**Comment by code-with-om** [comment]
Yes, I can work on this.
