### ISSUE TITLE
[Feature Request]: Support for custom channels

### ISSUE THREAD

**Issue by varun-heman** [OpenNyAI/Jugalbandi-Manager#17]
### Is your feature request related to a problem? Please describe.

Support for custom channels is missing

### Describe the solution you'd like

I'd like to link my own app or Web UI to JB-Manager, can we create a generic endpoint?

**Comment by KaranrajM** [comment]
@KaranrajM has to provide extra information about the description of the issue and make sure the relevant code is pushed to main and working.

**Comment by Lekhanrao** [comment]
@KaranrajM , as per Karan, this is already done, but existing only in Branch. Need to be merged into Main. Karan to do this.

**Comment by Lekhanrao** [comment]
@KaranrajM to complete this by 15th Oct

**Comment by Lekhanrao** [comment]
@KaranrajM working on it. ETA by 15th Oct
