### ISSUE TITLE
Issue: UI changes for JB Manager frontend with respect to channels

### ISSUE THREAD

**Issue by Lekhanrao** [OpenNyAI/Jugalbandi-Manager#176]
### Ticket Contents

To modify the existing UI page (JB Manager frontend) to allow for users to provide data for all channels (whatsapp/telegram/custom).

### Goals

Modify the JB Manager frontend UI page to allow inputs for different channels.

### Expected Outcome

The users should be able to select the channel that they want to install the bot in and provide appropriate keys.

### Acceptance Criteria

1. Create three different channels input components (Whatsapp, Telegram, custom) with required keys input boxes.
2. Successfully install the bot by running bash scripts/run.sh flow command after providing the input for a channel.

### Implementation Details

The current implementation only allows users to provide whatsapp channel related keys. Create different UI components to allow for user input for different channels and integrate it with the endpoints in api service.

### Mockups/Wireframes

<WILL BE UPDATED with Mockups>

### Product Name

Jugalbandi

### Organisation Name

OpenNyAI

### Domain

Legal

### Tech Skills Needed

Python, React

### Mentor(s)

@Lekhanrao @KaranrajM 

### Complexity

Medium

### Category

Frontend

**Comment by Lekhanrao** [comment]
@c4gt-community-support, What are the sub-category types and where do we update that in the Issue template?

**Comment by Ris-code** [comment]
@Lekhanrao could you please assign me this issue? I want to contribute.

**Comment by Lekhanrao** [comment]
Assigned ticket to @Ris-code

**Comment by Alekh-Srivastava** [comment]
Hey @Lekhanrao  I can work with the frontend react and alter it to allow user to directly enter the keys of the platform in which user want the bot  ,can I also take up the issue?

**Comment by Lekhanrao** [comment]
@Alekh-Srivastava , assigned this ticket to you as well. We'll pick the best solution. Thanks!

**Comment by Lekhanrao** [comment]
@Ris-code , any update on this please?

**Comment by Ris-code** [comment]
> @Ris-code , any update on this please?

Actually I am getting some sort of error while running the docker container. I am fixing it. Will post it here if its not fixed by evening.

**Comment by Ris-code** [comment]
![Screenshot 2024-08-14 155739](https://github.com/user-attachments/assets/55e983d9-fa2b-454b-b1ff-dd585f6d900e)
Here whenever I am trying to install the bot this error occurs. Whenever I click save the request is pending. How to fix this?

**Comment by KaranrajM** [comment]
> ![Screenshot 2024-08-14 155739](https://private-user-images.githubusercontent.com/95609173/357776916-55e983d9-fa2b-454b-b1ff-dd585f6d900e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODUsIm5iZiI6MTcyMzYzMTU4NSwicGF0aCI6Ii85NTYwOTE3My8zNTc3NzY5MTYtNTVlOTgzZDktZmEyYi00NTRiLWIxZmYtZGQ1ODVmNmQ5MDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZThlYjk4ZTg0MDNjMTY2MzE0MTg4NjVlZjE2NGFiZGJjYjU0MDBiMTk4YmM2NDA4MTUzYzVlZTQ3NzE1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pl74uPb-T46dkvAe-N5VN-JVqPTukAEgk2Fs8HL4nE8) Here whenever I am trying to install the bot this error occurs. Whenever I click save, the request is pending. How to fix this?

Hi @Ris-code the error that you are facing is because of kafka queues. Please check whether kafka is running in your machine and also double check the env values and try sourcing it as well before starting the application.

**Comment by Ris-code** [comment]
> > ![Screenshot 2024-08-14 155739](https://private-user-images.githubusercontent.com/95609173/357776916-55e983d9-fa2b-454b-b1ff-dd585f6d900e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODUsIm5iZiI6MTcyMzYzMTU4NSwicGF0aCI6Ii85NTYwOTE3My8zNTc3NzY5MTYtNTVlOTgzZDktZmEyYi00NTRiLWIxZmYtZGQ1ODVmNmQ5MDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZThlYjk4ZTg0MDNjMTY2MzE0MTg4NjVlZjE2NGFiZGJjYjU0MDBiMTk4YmM2NDA4MTUzYzVlZTQ3NzE1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pl74uPb-T46dkvAe-N5VN-JVqPTukAEgk2Fs8HL4nE8) Here whenever I am trying to install the bot this error occurs. Whenever I click save, the request is pending. How to fix this?
> 
> Hi @Ris-code the error that you are facing is because of kafka queues. Please check whether kafka is running in your machine and also double check the env values and try sourcing it as well before starting the application.

Actually, Kafka container has exited because it is saying create-topics. sh not found. When I saw it in the scripts directory, it was create-topic. sh was present but no create-topics. sh. So is it a name error? And I also changed the directory name from create-topic.sh to create-topics.sh but the issue remains the same.

**Comment by KaranrajM** [comment]
> > > ![Screenshot 2024-08-14 155739](https://private-user-images.githubusercontent.com/95609173/357776916-55e983d9-fa2b-454b-b1ff-dd585f6d900e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODUsIm5iZiI6MTcyMzYzMTU4NSwicGF0aCI6Ii85NTYwOTE3My8zNTc3NzY5MTYtNTVlOTgzZDktZmEyYi00NTRiLWIxZmYtZGQ1ODVmNmQ5MDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZThlYjk4ZTg0MDNjMTY2MzE0MTg4NjVlZjE2NGFiZGJjYjU0MDBiMTk4YmM2NDA4MTUzYzVlZTQ3NzE1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pl74uPb-T46dkvAe-N5VN-JVqPTukAEgk2Fs8HL4nE8) Here whenever I am trying to install the bot this error occurs. Whenever I click save, the request is pending. How to fix this?
> > 
> > 
> > Hi @Ris-code the error that you are facing is because of kafka queues. Please check whether kafka is running in your machine and also double check the env values and try sourcing it as well before starting the application.
> 
> Actually, Kafka container has exited because it is saying create-topics. sh not found. When I saw it in the scripts directory, it was create-topic. sh was present but no create-topics. sh. So is it a name error? And I also changed the directory name from create-topic.sh to create-topics.sh but the issue remains the same.

If you take a look at the kafka service configuration in docker-compose.yaml, it actually takes ./scripts/create-all-topics.sh and mounting it to /usr/bin/create-topics.sh inside the container. When running, it will try to run this file. So if the topics have already been created, can u remove the `& /usr/bin/create-topics.sh` from the command in docker-compose.yaml and try again?

**Comment by Ris-code** [comment]
> > > > ![Screenshot 2024-08-14 155739](https://private-user-images.githubusercontent.com/95609173/357776916-55e983d9-fa2b-454b-b1ff-dd585f6d900e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2MzE4ODUsIm5iZiI6MTcyMzYzMTU4NSwicGF0aCI6Ii85NTYwOTE3My8zNTc3NzY5MTYtNTVlOTgzZDktZmEyYi00NTRiLWIxZmYtZGQ1ODVmNmQ5MDBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE0VDEwMzMwNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyZThlYjk4ZTg0MDNjMTY2MzE0MTg4NjVlZjE2NGFiZGJjYjU0MDBiMTk4YmM2NDA4MTUzYzVlZTQ3NzE1M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Pl74uPb-T46dkvAe-N5VN-JVqPTukAEgk2Fs8HL4nE8) Here whenever I am trying to install the bot this error occurs. Whenever I click save, the request is pending. How to fix this?
> > > 
> > > 
> > > Hi @Ris-code the error that you are facing is because of kafka queues. Please check whether kafka is running in your machine and also double check the env values and try sourcing it as well before starting the application.
> > 
> > 
> > Actually, Kafka container has exited because it is saying create-topics. sh not found. When I saw it in the scripts directory, it was create-topic. sh was present but no create-topics. sh. So is it a name error? And I also changed the directory name from create-topic.sh to create-topics.sh but the issue remains the same.
> 
> If you take a look at the kafka service configuration in docker-compose.yaml, it actually takes ./scripts/create-all-topics.sh and mounting it to /usr/bin/create-topics.sh inside the container. When running, it will try to run this file. So if the topics have already been created, can u remove the `& /usr/bin/create-topics.sh` from the command in docker-compose.yaml and try again?

Thanks, its finally working. The bot is installed.

**Comment by Lekhanrao** [comment]
@KaranrajM , can we close this issue now?

**Comment by KaranrajM** [comment]
> @KaranrajM , can we close this issue now?

No, Lekha. The issue they are facing in their local system is just fixed. No PRs have been raised for this issue and not merged yet. So we cannot close this issue.

**Comment by yashpal2104** [comment]
Can you assign this to me, I can try to solve and make a PR for it

**Comment by Lekhanrao** [comment]
@yashpal2104, Assigned ticket to you as well.

**Comment by Ris-code** [comment]
```
>  => ERROR [frontend internal] load metadata for docker.io/library/node:21-bookworm                                                                                1.4s 
> ------
>  > [frontend internal] load metadata for docker.io/library/node:21-bookworm:
> ------
> failed to solve: node:21-bookworm: failed to resolve source metadata for docker.io/library/node:21-bookworm: error getting credentials - err: exit status 1, out: ``   
> Running docker-compose with existing images

```
why is this error occuring while building frontend. How to fix this ?

**Comment by KaranrajM** [comment]
> ```
> >  => ERROR [frontend internal] load metadata for docker.io/library/node:21-bookworm                                                                                1.4s 
> > ------
> >  > [frontend internal] load metadata for docker.io/library/node:21-bookworm:
> > ------
> > failed to solve: node:21-bookworm: failed to resolve source metadata for docker.io/library/node:21-bookworm: error getting credentials - err: exit status 1, out: ``   
> > Running docker-compose with existing images
> ```
> 
> why is this error occuring while building frontend. How to fix this ?

Hi @Ris-code it is a docker issue. Are you still facing this?

**Comment by Ris-code** [comment]
> > ```
> > >  => ERROR [frontend internal] load metadata for docker.io/library/node:21-bookworm                                                                                1.4s 
> > > ------
> > >  > [frontend internal] load metadata for docker.io/library/node:21-bookworm:
> > > ------
> > > failed to solve: node:21-bookworm: failed to resolve source metadata for docker.io/library/node:21-bookworm: error getting credentials - err: exit status 1, out: ``   
> > > Running docker-compose with existing images
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > why is this error occuring while building frontend. How to fix this ?
> 
> Hi @Ris-code it is a docker issue. Are you still facing this?

No, now its working fine.

**Comment by Ris-code** [comment]
![custom2](https://github.com/user-attachments/assets/548185a9-b521-4397-b468-f1d456d0b7eb)
![custom1](https://github.com/user-attachments/assets/106b6e43-d33f-43f6-9761-ec243169a903)
![tel2](https://github.com/user-attachments/assets/bca30813-410a-4571-b2d9-22e651ac261e)
![tel1](https://github.com/user-attachments/assets/b4fd4ee1-1dc6-41ee-aebd-f86b38c7c34d)
![wp2](https://github.com/user-attachments/assets/665668b1-8c6d-45ed-8633-60e7eb871be9)
![wp1](https://github.com/user-attachments/assets/385a9d77-43dc-44c1-82fc-694829f34f94)

These are the changes I have made to the frontend to add the channels. Do I need to make any modifications or open a PR?

**Comment by KaranrajM** [comment]
Hi @Ris-code I hope you have done the latest migration of the db tables. The screens look good. Can you confirm whether you are able to put the right data into the jb_channel table. Also can you test some sample bot with telegram after uploading the bot data?

**Comment by Ris-code** [comment]
> Hi @Ris-code I hope you have done the latest migration of the db tables. The screens look really good. Can you confirm whether you are able to put the right data into the jb_channel table. Also can you test some sample bot with telegram as it is easy to acquire telegram keys with BotFather after uploading the bot data? Let me know if you face any troubles. I am happy to walk you through the whole process.

No, not done yet. Will do it today.

**Comment by Ris-code** [comment]
> > Hi @Ris-code I hope you have done the latest migration of the db tables. The screens look really good. Can you confirm whether you are able to put the right data into the jb_channel table. Also can you test some sample bot with telegram as it is easy to acquire telegram keys with BotFather after uploading the bot data? Let me know if you face any troubles. I am happy to walk you through the whole process.
> 
> No, not done yet. Will do it today.

so for this do I need to make changes in the backend or test the key in any other python file ?

**Comment by shreypandey** [comment]
@KaranrajM Instead of making multiple UI components, can we make one unified UI which follows the bot and channel convention as well. Please refer #152 for this.

**Comment by KaranrajM** [comment]
Hi @Ris-code can you please check out the mocks present in issue #152 and follow the styling convention?

**Comment by Ris-code** [comment]
> Hi @Ris-code can you please check out the mocks present in issue #152 and follow the styling convention?

Ok, I will follow the same convention while building.

**Comment by Lekhanrao** [comment]
@Ris-code, Is there an update on this please?

**Comment by Lekhanrao** [comment]
@KaranrajM  this was worked by Tresvista. Karan to review the PR and close it by this week (latest by Friday, 4th Oct)
