### ISSUE TITLE
[Issue]: Lacking documentation for end-to-end setup & available data classes for functionalities (ex: retriever)

### ISSUE THREAD

**Issue by amant555** [OpenNyAI/Jugalbandi-Manager#22]
### Describe the issue

The current documentation falls short of providing comprehensive guidance on setup procedures and available classes for essential functionalities.

For instance:
- The end-to-end setup guide for the manager lacks crucial steps for deploying core functionalities, like configuring WhatsApp callbacks.
- The documentation fails to outline the functionalities offered by JB-Manager and the corresponding data classes necessary for building workflows. It lacks clarity on which parameters are required for specific functionalities.

To address these issues, the following actions are recommended:

**Documentation Update Tasks:**

- [x]  Enhance the documentation by incorporating detailed, step-by-step setup instructions.
- [x]  Refactor the code to automate callback setup and streamline end-to-end connections.
- [x]  Expand the documentation to provide comprehensive definitions of classes, along with illustrative examples of their usage

**Comment by shreypandey** [comment]
@amant555 We have added the step by step tutorial on the [quickstart guide](https://opennyai.github.io/Jugalbandi-Manager/tutorials/quickstart.html) along with screenshots.

The tutorial contains:-
1. Steps to run JBManager using existing images.
2. Adding FSM file (sample FSM is provided)
3. Setting up the bot using whatsapp credentials.
4. Setting up whatsapp callback.

**Comment by shreypandey** [comment]
We have added the instruction of FSM building [here](https://opennyai.github.io/Jugalbandi-Manager/how-tos/fsm_building.html)

**Comment by shreypandey** [comment]
Added the class documentation required for sending messages [here](https://opennyai.github.io/Jugalbandi-Manager/references/fsm-output.html).
