### ISSUE TITLE
[Bug]: Make Indexer service generic

### ISSUE THREAD

**Issue by sameersegal** [OpenNyAI/Jugalbandi-Manager#73]
### Describe the bug

Indexer service has some hard coded data for example it assumes that files are available on the local.

It does not get triggered by the API service. Make the API service receive files and write the files to the relevant location using common / helper methods #70 .

Assume the files are CSVs for now where all pre-processing has happened. 

Later: Upgrade this to parse PDFs etc and define a configurable strategy for preprocessing and indexing

**Comment by KaranrajM** [comment]
Merging this PR #151 will close this
