### ISSUE TITLE
[Feature Request]: Update QuickStart Tutorial  - Local Storage, Telegram with Indexer

### ISSUE THREAD

**Issue by sameersegal** [OpenNyAI/Jugalbandi-Manager#74]
### Is your feature request related to a problem? Please describe.

The current quick start tutorial is good but it has extra dependencies - Azure (Storage Account, Translation, etc.) and Whatsapp. It also doesn't show how Indexer / Retriever works.

CarWash while simple enough is not the typical bot we expect NGOs to deploy.

Let's make it better

### Describe the solution you'd like

After #70 is done, we can use local storage (docker volumes)
After #72  is done, we can use Telegram
After #73  is done, we can use Indexer to index some basic data

Create an example that has some structured flow but also has RAG.

**Comment by Lekhanrao** [comment]
- This also has a dependency on #152. 
- For Telegram integration Shrey is to update the documentation.

**Comment by Lekhanrao** [comment]
@KaranrajM, Can you pls review the status of this issue.
This is also related to issue #78

**Comment by Lekhanrao** [comment]
@DevvStrange , Functionalities are completed. Now the documentation have to be mapped to the Quick start tutorial. Lekha to check with Tresvista team if they can take this up.

**Comment by Lekhanrao** [comment]
@KaranrajM, is the related PR already merged? Can we close this issue?

**Comment by DevvStrange** [comment]
Closing this as the documentation is also updated in Quickstart Tutorial.
