### ISSUE TITLE
[Feature Request]: Reference for Indexing Strategies

### ISSUE THREAD

**Issue by sameersegal** [OpenNyAI/Jugalbandi-Manager#78]
### Is your feature request related to a problem? Please describe.

We need to provide tips on how to index data. This will include pre-processing, augmentation, chunking and anything in between. We must include the best links from the internet rather than creating our own

**Comment by Lekhanrao** [comment]
@KaranrajM , as discussed now, please update documentation for indexer.

**Comment by Lekhanrao** [comment]
Assigned ticket to @Sunandhita

**Comment by Sunandhita** [comment]
Yes sure ... will try to look into it parallelly as soon as possible

**Comment by Sunandhita** [comment]
This issue is completed from my end; raised PR for this... PR is under review

**Comment by Lekhanrao** [comment]
@Sunandhita Thanks Sunandhita. I am assuming the PR is with Karan or Arun for their review and merger?
